apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - databases.yaml
  - kafka-zipkin.yaml
  - keycloak.yaml
  - canary-rollouts.yaml
  - ecommerce-expansion.yaml
  - services.yaml
  - frontend.yaml
  - hpa.yaml
  - ingress/ingress.yaml
  - monitoring/namespace.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/grafana.yaml
  - monitoring/alertmanager.yaml
  - monitoring/alertmanager-slack-secret.yaml
images:
  - name: kaingyn615/product-service
    newName: hiunehihi/product-service
    newTag: main
  - name: kaingyn615/cart-service
    newName: hiunehihi/cart-service
    newTag: main
  - name: kaingyn615/payment-service
    newName: hiunehihi/payment-service
    newTag: main
  - name: kaingyn615/discovery-server
    newName: hiunehihi/discovery-server
    newTag: main
  - name: kaingyn615/api-gateway
    newName: hiunehihi/api-gateway
    newTag: main
  - name: kaingyn615/order-service
    newName: hiunehihi/order-service
    newTag: main
  - name: kaingyn615/inventory-service
    newName: hiunehihi/inventory-service
    newTag: main
  - name: kaingyn615/notification-service
    newName: hiunehihi/notification-service
    newTag: main
  - name: kaingyn615/admin-server
    newName: hiunehihi/admin-server
    newTag: main
  - name: kaingyn615/frontend
    newName: hiunehihi/frontend
    newTag: main
